[package]
name = "opusmeta"
version = "3.0.0"
edition = "2024"
description = "A Rust crate for reading and writing metadata to opus files"
license = "MIT"
repository = "https://github.com/karx1/opusmeta"
homepage = "https://karx.xyz/projects/opusmeta"
exclude = ["examples/"]

[dependencies]
base64 = "0.22"
infer = { version = "0.19.0", default-features = false }
ogg = "0.9"

[lints.clippy.pedantic]
level = "warn"
priority = -1
